DEPARTURE_PAGE STARTS_WITH s OR
    (
        (
            (CITY IS NEW DELHI OR CITY IS SANTA FE) AND
            (POSTAL_CODE IS 24540 OR POSTAL_CODE STARTS_WITH 11)

        ) OR CONTENT_CATEGORY_BOTTOM IS SWEATER OR DEPARTURE_PAGE IS HOME PAGE
    )